Javascript/app.js, index.html
I created a function to take user input, the question, and pass/fail functions which are called based on whether the test cases pass.
=> Input evaluation

Javascript/app.js, index.html
Created link in html, and initialized in JS.
Want to make sure this goes smoothly before doing anything else.
=> Added Firebase

login.css, login.html, login.js
login now pushes new user profiles to firebase
=> User profile push to firebase

Javascript/app.js
Added pseudocode to javascript file, with reference to Issue numbers in Github.
=> Pseudocode

login.js
this adds the function to change the player status to active on log in.  It also sets the robohash avatar url.
there need to be some edits to this to rectify with the master, it looks for state none currently, but its easy to change to joining
there is still no full game catch before log in
=> 11817 login edits

Javascript/app.js
added onDisconnect function, and also corrected setPlayerState function to use proper ref format / instead of .
=> Added onDisconnect Function

questions.json
Created a basic .json file that we can add questions to as people think of them.
=> Added question JSON file with starting questions

Javascript/app.js
=> wrote function to generate random question

Javascript/app.js
=> wrote function for resetting questions

Javascript/app.js
=> added change unasked to asked

login.js, project1testing-377b6-export.json
-player catch logic error solved
-full game function written
-clear current player info on logout
-push username to current player- request from terry
=> updated login

CSS/style.css, Javascript/app.js, index.html
Fixed code formatting across all main files.
=> Fixing ids

Javascript/app.js
Wrote function for Issue #30 to trigger random question grab
=> Trigger question grab

CSS/style.css, Javascript/app.js, index.html
Removed the "Login with Github button", as well, since that's no longer on the table.
=> Corrected html and css files

Javascript/app.js
Added functions for Issue #40 and #59 , to grab new question, update FB with that question number, and pull question locally when it changes.
=> Set new question

Javascript/app.js
Restructured the Firebase functions. 
Also added new Pseudocode, and removed the helper functions that we no longer needed.
=> Changed Firebase reference functions

CSS/style.css, Javascript/app.js
Created functions to run when code passes or fails tests. Also added function to update the page with the current question, and pre-populate the text area with the function skeleton.
=> Pass or fail

Javascript/app.js
Wrote functions to start a 100ms interval for checks, listen for code updates to opponent code, push changes of player code, and update opponent code from FB data
=> Working Code Updates

CSS/style.css, Javascript/app.js, index.html
Changed html element references to match new page. 
Added a check code button, and a handler function for when that's clicked.
=> Updating elements

Javascript/app.js
set the text areas to allow a tab by using Sam's captureTabPress function that he had already written
=> Invoked captureTabPress function

Javascript/app.js
Tested and fixed functions to pull questions from Firebase, and reset questions to asked.
=> Question test

CSS/style.css, Javascript/app.js, index.html
For use in login screen failures.  Pass it a string to display the message
=> Created Alert Modal

login.js
everything is on an object now, the only global function called is db
i put in the calls to the object for you so this should be cut and paste
i debugged this, let me know if you see anything esle
=> Make object

CSS/style.css, Javascript/app.js
Fixed the worker errors so the fail function is only called once.
=> Worker return fix

Javascript/app.js
Merged Kyle's login object into the app.js file.
=> Login merge

Javascript/app.js
Functions for a timer to countdown and update the question area with a display message.  Can be used when starting the game, or between questions to update the UI
=> Basic Timer

CSS/style.css, index.html
Adjusted colors, font, form submission highlights for readability.
=> UI Adjustments

Javascript/app.js
=> State handling

CSS/style.css, index.html
Changed highlight colors, disabled spellcheck, adjusted tab character spacing
=> Added textarea format

CSS/style.css, Javascript/app.js, index.html, questions.json
Added functions to start a new round, increment score, and remove data on signout.
=> Start new round

Javascript/app.js, index.html
=> added giphy function to complete project requirements

questions.json, unit-testing-questions/questions.js
Finish 15 questions in question bank
=> Questions2

CSS/style.css, README.md
On login page, hover status was set to display a blue color.  Made it consistent with the rest of the design
=> Removed blue button effect

CSS/style.css
It was in the deleted section and needed to be re-added to the correct location to function
=> Re-added h5 font size
